name: Build Linux AppImage

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            fuse \
            libfuse2 \
            wget

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Get packages
        run: flutter pub get

      - name: Build Linux app
        run: flutter build linux --release

      - name: Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/

      - name: Build AppImage
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --output appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Knife-AppImage
          path: ./*.AppImage
